version: 0.0
os: linux
files:
  - source: aws_vpc/aws-flask
    destination: /home/ec2-user/sample-app
hooks:
  ApplicationStop:
    - location: aws_vpc/code-deploy/stop_server.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: aws_vpc/code-deploy/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: aws_vpc/code-deploy/install_pip_requirements.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: aws_vpc/code-deploy/start_server.sh
      timeout: 300
      runas: root
