
version: 0.0
os: linux
files:
  - source: /aws_vpc/eb-flask
    destination: /home/ec2-user/sample-app
hooks:
  AfterInstall:
    - location: code_deploy_scripts/install_dependencies
      timeout: 300
      runas: root
  ApplicationStart:
    - location: code_deploy_scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
