jobs:
  tests:
    docker:
      - image: cimg/python:3.9.8
    steps:
      - checkout # checkout source code
      - run:
          name: Check python version and install dependencies
          command: |
                python --version
                pip install -r requirements_dev.txt
                pip install -r aws_vpc/eb-flask/requirements.txt
      - run:
          name: Run tests
          command: python -m pytest tests/
      - store_artifacts:
          path: ~/tests
workflows:
  version: 2
  tests:
    jobs:
      - tests
