jobs:
  tests:
    docker:
      - image: cimg/python:3.9.8
    steps:
      - checkout # checkout source code
      - run:
          name: Check python version and install tox
          command: |
                python --version
                pip install tox
      - run:
          name: Run tests
          command: python -m tox
      - store_artifacts:
          path: ~/tests
workflows:
  version: 2
  tests:
    jobs:
      - tests
