jobs:
  tests:
    docker:
      - image: cimg/python:3.9.8
    steps:
      - checkout # checkout source code
      - run:
          name: Install dependencies
          command: |
                python --version
                python -m pip install -r aws_vpc/eb-flask/requirements.txt
                python -m pip install -r requirements_dev.txt
      - run:
          name: Run tests
          command: tox
      - store_artifacts:
          path: ~/tests
workflows:
  version: 2
  tests:
    jobs:
      - tests
