Description: "This template creates a nested stack with redshift resource in a vpc, rds/ec2 resources in another vpc and a batch job definition/queue"
Parameters:
  RDSDBName:
    Default: dev
    Description: "RDS DB name"
    Type: String
    MinLength: '1'
    MaxLength: '64'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: Must begin with a letter and contain only alphanumeric characters.
  RDSEngine:
    Default: postgres
    Description: RDS db engine e.g. postgres, mysql, mariadb, sqlserver
    Type: String
    AllowedValues:
      - mysql
      - postgres
      - oracle-se
  RDSDBUsername:
    Description: Username for RDS database access
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  RDSDBPassword:
    Description: RDS Password database access
    Type: String
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: must contain only alphanumeric characters.
  RedshiftUsername:
    Description: Redshift Username database access
    Type: String
  RedshiftPassword:
    Description: Redshift Password database access
    Type: String
  RDSDBAllocatedStorage:
    Default: '20'
    Description: The size of the RDS database (GiB)
    Type: Number
    MinValue: '20'
    MaxValue: '50'
    ConstraintDescription: must be between 20 and 50 GiB.
  UserIP:
      AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
      ConstraintDescription: "It must be a valid IP CIDR range of the form x.x.x.x/x. Suggest to enable access to your IP address only. Pls get your address using checkip.amazonaws.com or whatsmyip.org."
      Description: "The IP address range that can be used to connect to the RDS instances from your local machine.It must be a valid IP CIDR range of the form x.x.x.x/x.Pls get your address using checkip.amazonaws.com or whatsmyip.org"
      Type: "String"
  InstanceType:
      Default: 't2.micro'
      Description: EC2 Instance type to use. Default is t2.micro
      Type: String
  CreateElasticIP:
    Description: Whether to associate elastic ip for EC2
    Type: String
    Default: false
Resources:
  NestedRDSStack:
    Type: 'AWS::CloudFormation::Stack'
    DeletionPolicy: Retain
    Properties:
      TemplateURL: >-
        https://cf-templates-wnxns0c4jjl4-us-east-1.s3.amazonaws.com/rds-resource.yaml
      Parameters:
          DBName: !Ref RDSDBName
          DBEngine: !Ref RDSEngine
          DBUsername: !Ref RDSDBUsername
          DBPassword: !Ref RDSDBPassword
          Subnet1: !ImportValue vpc-non-default-private-subnet-1
          Subnet2: !ImportValue vpc-non-default-private-subnet-2
          VPC: !ImportValue vpc-non-default-id
          ClientIP: !Ref UserIP
          EC2Security:
                Fn::GetAtt:
                    - NestedEC2Stack
                    - Outputs.EC2SecurityGroup
  NestedRedshiftStack:
    Type: 'AWS::CloudFormation::Stack'
    DeletionPolicy: Retain
    Properties:
      TemplateURL: >-
        https://cf-templates-wnxns0c4jjl4-us-east-1.s3.amazonaws.com/redshift.yaml
      Parameters:
          Username: !Ref RedshiftUsername
          Password: !Ref RedshiftPassword
          ClientIP: !Ref UserIP
          EC2Security:
              Fn::GetAtt:
                  - NestedEC2Stack
                  - Outputs.EC2SecurityGroup
  NestedEC2Stack:
    Type: 'AWS::CloudFormation::Stack'
    DeletionPolicy: Retain
    Properties:
      TemplateURL: >-
        https://cf-templates-wnxns0c4jjl4-us-east-1.s3.amazonaws.com/ec2.yaml
      Parameters:
          Subnet: !ImportValue vpc-non-default-pubic-subnet-1
          VPC: !ImportValue vpc-non-default-id
          ClientIP: !Ref UserIP
          InstanceTypeParameter: !Ref InstanceType
          Elasticip: !Ref CreateElasticIP
  NestedBatchStack:
      Type: 'AWS::CloudFormation::Stack'
      DeletionPolicy: Retain
      Properties:
          TemplateURL: >-
              https://cf-templates-wnxns0c4jjl4-us-east-1.s3.amazonaws.com/batch-job.yaml
          Parameters:
              DBName: !Sub "${RDSEngine}${RDSDBName}"
              DBUser: !Ref RDSDBUsername
              DBPassword: !Ref RDSDBPassword
              Host:
                  Fn::GetAtt:
                      - NestedRDSStack
                      - Outputs.EndpointAddress
              Port:
                  Fn::GetAtt:
                      - NestedRDSStack
                      - Outputs.Port
              Subnet: !ImportValue vpc-non-default-pubic-subnet-2
              SecurityGroup:
                  Fn::GetAtt:
                      - NestedEC2Stack
                      - Outputs.EC2SecurityGroup
