Description: "This example template creates a single node cluster with requested node type"
Parameters:
  NodeType:
    Description: "Type of node in redshift cluster. Only allow nodes whose pricing < $1/hr in US-east region"
    Default: dc2.large
    AllowedValues:
      - ds2.xlarge
      - dc1.large
      - dc2.large
    Type: "String"
  DB:
    Description: "Name of db"
    Default: dev
    Type: "String"
  Username:
    Description: "Master username"
    Type: "String"
  Password:
    Description: "Master password"
    Type: "String"
Resources:
  RedshiftCluster:
    Type: "AWS::Redshift::Cluster"
    Properties:
      DBName:
        Ref: "DB"
      MasterUsername:
        Ref: "Username"
      MasterUserPassword:
        Ref: "Password"
      NodeType:
        Ref: "NodeType"
      ClusterType: "single-node"
      ClusterIdentifier: "default-cluster"
      Port: "8192"
      ClusterParameterGroupName:
        Ref: "RedshiftClusterParameterGroup"
      ClusterSubnetGroupName:
        Ref: "RedshiftSubnetGroup"
  RedshiftClusterParameterGroup:
    Properties:
      Description: "Cluster parameter group"
      ParameterGroupFamily: "redshift-1.0"
      Parameters:
        - { ParameterName: "enable_user_activity_logging", ParameterValue: "true"}
    Type: "AWS::Redshift::ClusterParameterGroup"
  RedshiftSubnetGroup:
    Type: "AWS::Redshift::ClusterSubnetGroup"
    Properties:
      Description: "Subnet Group available for the default Redshift Cluster"
      SubnetIds:
        - Ref: NestedVPCStack.PublicSubnet1
        - Ref: NestedVPCStack.PublicSubnet2
  NestedVPCStack:
    Type: 'AWS::CloudFormation::Stack'
    DeletionPolicy: Retain
    Properties:
      TemplateURL: >-
        https://s3.amazonaws.com/cloudformation-templates-us-east-1/VPC-stack.template
