AWSTemplateFormatVersion: "2010-09-09"
Description: "Security groups and subnets"
Parameters:
    RedshiftDefaultSecurityGroup:
        Description: The id of redshift security group id attached to default VPC
        Type: String
        AllowedPattern: 'sg-[a-zA-Z0-9]*'
        ConstraintDescription: must begin with sg- and contain alphanumeric characters
    EC2DefaultSecurityGroup:
        Description: The id of EC2 security group id attached to default VPC
        Type: String
        AllowedPattern: 'sg-[a-zA-Z0-9]*'
        ConstraintDescription: must begin with sg- and contain alphanumeric characters
Resources:
  VPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: "10.192.0.0/16"
      Tags:
        - Key: Name
          Value: vpc-ec2-rds-redshift
  PublicSubnet1:
    Type: "AWS::EC2::Subnet"
    Properties:
      CidrBlock: "10.192.10.0/24"
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      VpcId:
        Ref: "VPC"
      Tags:
        - Key: Name
          Value: "PublicSubnet1"
  PublicSubnet2:
    Type: "AWS::EC2::Subnet"
    Properties:
      CidrBlock: "10.192.11.0/24"
      AvailabilityZone: !Select [ 1, !GetAZs  '' ]
      VpcId:
        Ref: "VPC"
      Tags:
        - Key: Name
          Value: "PublicSubnet2"
  PrivateSubnet1:
    Type: "AWS::EC2::Subnet"
    Properties:
      CidrBlock: "10.192.20.0/24"
      AvailabilityZone: !Select [ 0, !GetAZs  '' ]
      MapPublicIpOnLaunch: false
      VpcId:
        Ref: "VPC"
      Tags:
        - Key: Name
          Value: "PrivateSubnet1"
  PrivateSubnet2:
    Type: "AWS::EC2::Subnet"
    Properties:
      CidrBlock: "10.192.21.0/24"
      AvailabilityZone: !Select [ 1, !GetAZs  '' ]
      MapPublicIpOnLaunch: false
      VpcId:
        Ref: "VPC"
      Tags:
        - Key: Name
          Value: "PrivateSubnet2"
  InternetGateway:
    Type: "AWS::EC2::InternetGateway"
    Properties:
      Tags:
        - { Key: "Application", Value: "non-default" }
  NatGateway1EIP:
    Type: AWS::EC2::EIP
    DependsOn: AttachGateway
    Properties:
      Domain: vpc
  NatGateway2EIP:
    Type: AWS::EC2::EIP
    DependsOn: AttachGateway
    Properties:
      Domain: vpc
  NATGateway1:
    Type: "AWS::EC2::NatGateway"
    Properties:
      AllocationId: !GetAtt NatGateway1EIP.AllocationId
      SubnetId:
        Ref: "PublicSubnet1"
      Tags:
        - Key: "Application"
          Value: "non-default"
  NATGateway2:
    Type: "AWS::EC2::NatGateway"
    Properties:
      AllocationId: !GetAtt NatGateway2EIP.AllocationId
      SubnetId:
        Ref: "PublicSubnet2"
      Tags:
        - Key: "Application"
          Value: "non-default"
  S3GatewayEndpoint:
    Type: 'AWS::EC2::VPCEndpoint'
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: '*'
            Action:
              - 's3:*'
            Resource:
              - '*'
      RouteTableIds:
        - !Ref PublicRouteTable
        - !Ref PrivateRouteTable1
        - !Ref PrivateRouteTable2
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.s3'
      VpcId:
        Ref: "VPC"
  AttachGateway:
    Type: "AWS::EC2::VPCGatewayAttachment"
    Properties:
      InternetGatewayId:
        Ref: "InternetGateway"
      VpcId:
        Ref: "VPC"
  PrivateRouteTable1:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
  PrivateRouteTable2:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
  PrivateRoute1:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable1
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NATGateway1
  PrivateRoute2:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable2
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NATGateway2
  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
  PrivateSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable1
      SubnetId: !Ref PrivateSubnet1
  PrivateSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable2
      SubnetId: !Ref PrivateSubnet2
  PublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet1
  PublicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet2
  RDSSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
          GroupDescription: "RDS for non-default VPC"
          VpcId:
              Fn::GetAtt:
                  - NestedVPCStack
                  - Outputs.VPC
          SecurityGroupIngress:
              -   IpProtocol: tcp
                  FromPort: 5432
                  ToPort: 5432
                  CidrIp: !Ref ClientIP
              -   IpProtocol: tcp
                  FromPort: 1433
                  ToPort: 1433
                  CidrIp: !Ref ClientIP
              -   IpProtocol: tcp
                  FromPort: 0
                  ToPort: 65535
                  SourceSecurityGroupId:
                      Fn::GetAtt:
                            -  "EC2SecurityGroup"
                            -  "GroupId"
              -   IpProtocol: tcp
                  FromPort: 0
                  ToPort: 65535
                  SourceSecurityGroupId:
                      Fn::GetAtt:
                          - "RedshiftDefaultSecurityGroup"
                          - "GroupId"
              -   IpProtocol: tcp
                  FromPort: 0
                  ToPort: 65535
                  SourceSecurityGroupId:
                      Fn::GetAtt:
                          - "EC2DefaultSecurityGroup"
                          - "GroupId"
              -   IpProtocol: icmp
                  FromPort: 8
                  ToPort: -1
                  CidrIp: !Ref ClientIP
          SecurityGroupEgress:
              -   CidrIp: "0.0.0.0/0"
                  IpProtocol: "-1"
  EC2SecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
          GroupDescription: "EC2 for non-default VPC"
          VpcId:
              Fn::GetAtt:
                  - NestedVPCStack
                  - Outputs.VPC
          SecurityGroupIngress:
              -   IpProtocol: tcp
                  FromPort: 0
                  ToPort: 65535
              -   IpProtocol: icmp
                  FromPort: 8
                  ToPort: -1
                  CidrIp: !Ref ClientIP
              -   IpProtocol: tcp
                  FromPort: 22
                  ToPort: 22
                  CidrIp: !Ref ClientIP
              -   IpProtocol: tcp
                  FromPort: 80
                  ToPort: 80
                  CidrIp: "0.0.0.0/0"
              -   IpProtocol: tcp
                  FromPort: 443
                  ToPort: 443
                  CidrIp: "0.0.0.0/0"
          SecurityGroupEgress:
              -   CidrIp: "0.0.0.0/0"
                  IpProtocol: "-1"
Outputs:
  VPC:
    Description: A reference to the created non-default VPC
    Value: !Ref VPC

  PublicSubnets:
    Description: A list of the public (non-default) subnets
    Value: !Join [ ",", [ !Ref PublicSubnet1, !Ref PublicSubnet2]]

  PrivateSubnets:
    Description: A list of the private (non-default) subnets
    Value: !Join [ ",", [ !Ref PrivateSubnet1, !Ref PrivateSubnet2 ] ]

  PublicSubnet1:
    Description: A reference to the non-default public subnet in the 1st Availability Zone
    Value: !Ref PublicSubnet1

  PublicSubnet2:
    Description: A reference to the non-default public subnet in the 2nd Availability Zone
    Value: !Ref PublicSubnet2

  PrivateSubnet1:
    Description: A reference to the non-default private subnet in the 1st Availability Zone
    Value: !Ref PrivateSubnet1

  PrivateSubnet2:
    Description: A reference to the non-default private subnet in the 2nd Availability Zone
    Value: !Ref PrivateSubnet2

  RDSSecurityGroup:
      Description: A reference to the RDS Security group created for non default vpc
      Value: !Ref RDSSecurityGroup

  EC2SecurityGroup:
      Description: A reference to the security group created for EC2 in non-default vpc
      Value: !Ref EC2SecurityGroup
